# Site settings
title: Travel Blog
email: funTravel@gmail.com
description: A fun blog about traveling.
baseurl: "/travel-blog"
twitter_username: guilh 
avatar: "https://pbs.twimg.com/profile_images/578368788535455744/WhLtbEaB.jpeg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Guil Hernandez" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
